           - name: Save data
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@bot.com"
          git add -A
          git diff --staged --quiet || git commit -m "Update finance data"
          git pull --rebase origin main
          git push

